### PR TITLE
s22-6pm-3 - dj - add end date to commons backend 3

### PR DESCRIPTION
**Pull request by D-Jerez**
# Overview

Adds an endDate field to Commons backend.
This time, this branch was made off of the main branch, instead of another PR. Also, there are no parentheses in the branch name. 

# Issues Addressed

Addresses Issue #57 

# Details

The Commons backend api now returns an endDate for each commons, which could be used in the future to implement a countdown for the number of days left in a commons.

# Test Plan (for interactive testing)

* Load the page onto localhost:8080
* Go to the Swagger UI page
* Use sample PUT and GET requests to confirm that you get an endDate

Coverage:
image

Mutation testing:
image

### CODE REVIEW

**Review by zackmarks — APPROVED** [review]
LGTM

**Review by mitchly — APPROVED** [review]
LGTM, please change ur pr title tho ty

**Review by YoshiShah — DISMISSED** [review]
LGTM

**Review by mitchly — DISMISSED** [review]
LGTM

**Review by zackmarks — APPROVED** [review]
LGTM

**Review by mitchly — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
