### PR TITLE
s22-6pm-3 - ml - add user leaderboard button onto play page + test

### LINKED ISSUE #10: 6pm-3 Add a Leaderboard button on the Play Page
On the play page, add a button that goes to the leaderboard for the commons. For this issue , the leaderboard can be a placeholder page.

# Acceptance Criteria
- [x] Make a placeholder page for leaderboard if leaderboard page has not been created
- [x] Create a button on the play page
- [x] Link it to the leaderboard page
- [x] This feature works as expected on localhost
- [x] This feature works as expected on heroku
- [x] There is full test coverage (Jacoco) for the new code
- [x] There is full mutation test coverage (Pitest) for new code

### PR DESCRIPTION
**Pull request by mitchly**
# Overview

This pull request adds a button for access to the commons id specific leaderboard on the play page. Along with it is a test that ensures that the button functions as intended (is it there, is it clickable, does it route properly).

This pull request also contains code merged from the branch yl-4-alterLBTable for access to the leaderboardFixture.js. The code for the branch is part of a different pull request.

# Issues Addressed

Closes #10 

# Details

Localhost Testing: The button works as intended. (See search bar)
Screen Shot 2022-06-02 at 2 32 49 AM
Screen Shot 2022-06-02 at 2 32 56 AM

Heroku Testing: The button works as intended. (See search bar)
Screen Shot 2022-06-02 at 8 08 33 AM
Screen Shot 2022-06-02 at 8 08 39 AM

Test Coverage: Leaderboard is all 0's because it is an empty file used to ensure routing worked as intended.
Screen Shot 2022-06-02 at 1 14 39 PM

Mutation Tests:
Screen Shot 2022-06-02 at 1 30 19 PM

# Test Plan (for interactive testing)

To test, go on localhost or heroku and find the play page. Clicking on the button should route the user to a new page where the leaderboard table should be seen.

### CODE REVIEW

**Review by D-Jerez — APPROVED** [review]
LGTM

**Review by YoshiShah — DISMISSED** [review]
LGTM

**Review by YoshiShah — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
I'm approving this even though it introduces a bug.. namely that non-admins can see the leaderboard button in cases where the commons has the showLeaderboard flag set to false.

I'm discounting it to 5 points instead of 10; and you can earn the other 5 if you fix that.

You can also get 5 more along with that if you fix a related bug; that the leaderboard shows up if you type in the URL in the URL bar for non-admins when the showLeaderboard is set to false.

I put the proposed fixes in the slack chat; you can submit another PR with those two fixes for 10 additional points.

**Pull request merged**
