### PR TITLE
s22-6pm-4 Adrian - fixes undefined toast message in admin edit commons

### LINKED ISSUE #87: BUG: Toast has invalid data after editing a commons
* STR (steps to reproduce):

1. Create a commons
2. Go to List Commons
3. Click Edit
4. Make a change, and click Update

* Expected: Toast message has valid data
* Observed: Invalid data in toast message:

image

### PR DESCRIPTION
**Pull request by adrianlindell**
In this PR we fix the bug in admin edit commons that sends a Toast message with undefined parameters by removing the parameters from the message. I came to this solution by TA's recommendation as we could not find a simple way of returning the edited commons so that the Toast message can access its parameters.

Before:
image
After:
image

Closes #87

### CODE REVIEW

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Comment by sangitakunapuli** [comment]
good bug fix - ready to merge!

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
Mergeable when CI/CD is green

**Pull request merged**
