### PR TITLE
6pm 3 - Add codecov token to readme

### PR DESCRIPTION
**Pull request by zackmarks**
added a new codecov badge.

old badge:
[codecov](https://codecov.io/gh/ucsb-cs156-w22/team04-w22-6pm-HappyCows)
new badge:
[codecov](https://codecov.io/gh/ucsb-cs156-s22/s22-6pm-happycows)

### CODE REVIEW

**Comment by zackmarks** [comment]
please give 5 points. thank you and have a nice day

**Review by mitchly — COMMENTED** [review]
LGTM

**Review by Yvonneliu0201 — APPROVED** [review]
lgtm

**Review by mitchly — APPROVED** [review]
LGTM

**Review by andrewhlu — APPROVED** [review]
LGTM!

**Pull request merged**
