### PR TITLE
6pm-4, sk - updated heroku production deployment url in readme file

### LINKED ISSUE #5: 6pm-4 Set up production Heroku deployment
- [x] There is a production deployment on Heroku of this repo
- [x] The name of the Heroku deployment has the name `s22-6pm-happycows`
- [x] There is a separate branch in the repo to work on this issue
- [x] The app has been deployed on Heroku
- [x] There is a link to the Heroku dashboard for this repo in the README.md
- [x] All of alu@ucsb.edu, kheffernan@ucsb.edu, bzamoraflores@ucsb.edu, andrewpeng@ucsb.edu, phtcon@ucsb.edu are added to the production deployment
- [x] All of alu@ucsb.edu, kheffernan@ucsb.edu, bzamoraflores@ucsb.edu, andrewpeng@ucsb.edu, phtcon@ucsb.edu are added to the list of admins on the production deployment

### PR DESCRIPTION
**Pull request by sangitakunapuli**
# Overview

In this PR, we add the heroku production deployment link to the README file. The main branch has been deployed to Heroku and all of the relevant mentors/professors and collaborators have been added to both the Heroku repository and ADMIN_EMAILS config variable. The Heroku deployment of happy cows 6pm is up and running!

# Issues Addressed

This PR closes #5 (setting up a production deployment on Heroku).

### CODE REVIEW

**Review by neelmurthy1 — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
> LGTM

Please see: https://ucsb-cs156.github.io/topics/code_reviews_github/

**Review by laszlo-tw — APPROVED** [review]
lgtm 😺

**Comment by pconrad** [comment]
5 pts for setting up heroku deployment and updating readme, and 5 for setting up oauth credentials.

**Pull request merged**
