### PR TITLE
s22-6pm-4 nm - add degradationRate to form and table components

### LINKED ISSUE #24: s22-6pm-4 Add field degradation rate to fixtures, form components, table components
- [x] There is a field in the fixtures for degradation rate as a decimal number treated as a percentage EDIT: NO LONGER NEEDED
- [x] There is a field in the form components for degradation rate as a decimal number treated as a percentage 
- [x] There is a field in the table components for degradation rate as a decimal number treated as a percentage
- [x] There is a field called "degradation rate" on the create commons, edit commons, and commons list page
- [x] For now, if the API doesn't return this, and your code depends on it, you can add code that adds a fake value of 0.1 into the data returned by the backend; once the API is ready, you can back this code out.
- [x] For acceptance, the actual API values should be used instead of the fake values

### PR DESCRIPTION
**Pull request by neelmurthy1**
# Overview

Closes #24

Added degradationRate field in CommonsTable.js.
Added degradationRate field in CommonsForm.js.
Adjusted tests for both of the above files to look for degradationRate field.

~NOTE: The frontend tests fail for the AdminEditCommonsPage.js, which inherits from CommonsForm.js. However, they fail for CommonsTable.js.test and CommonsForm.js.test~

Previously, we had failing CI/CD tests but in the most recent commit to this branch, we have added the degradationRate field to the AdminCreateCommonsPage and associated frontend tests and AdminEditCommonsPage and associated tests. This has solved the issue - the frontend tests now all pass.

On Storybook, the degradation field shows up as expected on the form and is visible through fixtures: 

For Users:
Screen Shot 2022-06-01 at 10 57 13 PM

For Admin:
Screen Shot 2022-06-01 at 10 57 43 PM

In the CommonsForm:
Screen Shot 2022-06-01 at 10 58 26 PM
Screen Shot 2022-06-01 at 10 59 02 PM

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM.. will need to be tested on QA

**Review by pconrad — DISMISSED** [review]
CI/CD is failing .. that needs to be addressed.

**Review by laszlo-tw — APPROVED** [review]
lgtm!! good job sangita and neel!!! 🐶🐱

**Review by laszlo-tw — APPROVED** [review]
lgtm!! 🎃-laszlo

**Review by laszlo-tw — APPROVED** [review]
LGTM! CI/CD issues have been resolved by SK's recent commits which have fixed frontend tests.

-laszlo

**Comment by laszlo-tw** [comment]
@pconrad CI/CD issues were fixed with commit 4b52ebd2cc2836f0f630498e7702d010d15260cf (
sk - fixed admin edit/create commons tests to include degradation rat) 😺

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
