### PR TITLE
s22-6pm-3 Changed Columns in LeaderboardTable.js + Adopted those Changes to Tests and Storybook + Fixed Bug with Profits

### LINKED ISSUE #11: 6pm-3 Add a React component for a leaderboard table
Add a React component for a leaderboard table. It should take a players array in the format for the leaderboard fixtures. Make sure it's in the storybook. The built in features of the table will allow sorting by cows, health, money, etc.

(* Similar to UCSBDiningCommons table from team03, I'm guessing *)

# Acceptance Criteria
- [x] Create a React component for a `leaderboard` table
- [x] Takes in a `players` array, meaning the table holds players
- [x] Include this component to Storybook
- [x] Implement features that will allow sorting by cows, health, money, etc.
- [x] The feature works as expected on localhost.
- [x] The feature works as expected when deployed to Heroku.
- [x]  There is full test coverage (Jacoco) for the new code
- [x] There is full mutation test coverage (Pitest) for new code

### PR DESCRIPTION
**Pull request by Yvonneliu0201**
# Overview
Yvonne removed 'cowHealth' and 'fullName'  from `Leaderboard.js` and added a 'userId' column to the table. 
Yvonne created a new file `leaderboardFixtures.js` that has lists of userCommons with 'userId' and 'commonsId' based on the userCommons entity for corrected testing and storybook.
Yvonne edited `LeaderboardTable.stories.js` and `LeaderboardTable.test.js` to reflect the changes to the columns.

Ayush added a function to profitscontroller.java to facilitate the backend request using commonsId.
Ayush fixed an error in the  PlayPage.js where it was incorrectly making a backend request using the wrong variable(using commonsId instead of userCommonsId).

# User Stories
- As a user, I can view the list of users and just their stats (ie. userId, numCows, wealth) in any commons that I am currently in.
- As an admin, I can view the list of users and their stats+usercommonsid in any commons that I am currently in.

# Issues Addressed
Closes #11

# Code details / modifications:
- Edited `LeaderboardTable.js` where I created a table that includes columns: 'User Id', 'Cows Owned', and 'Wealth', and '(Admin) userCommons Id' if you are an admin.
- Altered `LeaderboardTable.stories.js` where on Storybook, I created 7 instances of the Leaderboard table. One with nothing in it, a second with 1 user, a third with 3 users, a fourth with 5 users, a fifth with 10 users, a sixth with 3 users viewing as admin, and a seventh with 5 users viewing as admin. I used the `leaderboardFixtures.js` instead of `userCommonsFixtures.js`
- Changed `LeaderboardTable.test.js` where it tests the expected outputs for a user and admin when viewing the Leaderboard table in various states (empty or filled).
- Fixed an error in the  PlayPage.js where it was incorrectly making a backend request using the wrong variable(using commonsId instead of userCommonsId)
- Added a function to profitscontroller.java to facilitate the backend request using commonsId

# Test Plan (for interactive testing)

* Load the page onto localhost:8080
* Run npm run storybook and view how a user/admin should view the table.
* Join a user commons and see that their is no toast error when visiting a commons on heroku

Code Coverage:
image

Mutation Testing:
image

# Notes!
- An additional feature that could be added to `LeaderboardTable.js` would be to call the backend and use the 'userId' to grab and display their full name. However the issue would be how to reflect 'calling the backend' when using fixtures to test and create stories.

# Further Details 
**Storybook Demonstration w/ ten userCommons as an Admin**
image

### CODE REVIEW

**Review by zackmarks — DISMISSED** [review]
LGTM

**Review by D-Jerez — DISMISSED** [review]
LGTM

**Review by zackmarks — APPROVED** [review]
lgtm

**Review by pconrad — APPROVED** [review]
LGTM!  I really like the feature of showing the id for admins, but not for regular users!

**Comment by YoshiShah** [comment]
LGTM

**Review by YoshiShah — APPROVED** [review]
LGTM

**Review by zackmarks — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
The code looks good!  I'll need to test on QA before merging, but for now LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
